error.bucket_exists=bucket already exist, please do not repeat the submission